### ISSUE TITLE
Pull data from an Excel sheet1 (with dataframe starting from a cell) into an another sheet

### ISSUE THREAD

**Issue by abhi3700** [ZoomerAnalytics/xlwings#1019]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.1, MS Excel 2016

#### Describe your issue (incl. Traceback!)
Actually, I want to pull data from a sheet (starting from cell A9) of an excel like [this](https://github.com/abhi3700/my_todo-list/blob/master/ASH09_QC_LOG_BOOK.xlsm) into a different sheet (starting from cell A1).

**Cell start_range**: A9
**Source sheet:** ASFE1-ER

**Destination sheet:** ER Plot
**Cell start_range**: A1

I am taking the help of pandas dataframe, read_excel. 
But none is helping me get out of this.

Issue:
```py
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "h:\excel\dryetch\macro_enabled_logbooks\ash09_qc_log_book\ASH09_QC_LOG_BOOK.py", line 33, in main

    pd.read_excel("H:\\excel\\dryetch\\macro_enabled_logbooks\\ASH09_QC_LOG_BOOK\\ASH09_QC_LOG_BOOK.xlsm", sheetname='ASFE1-ER'), header=1, index=False

  File "C:\Users\abhijit\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 1491, in value

    return conversion.read(self, None, self._options)

  File "C:\Users\abhijit\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\conversion\__init__.py", line 25, in read

    pipeline = accessors.get(convert, convert).reader(options)

  File "C:\Users\abhijit\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 879, in __hash__

    ' hashed'.format(self.__class__.__name__))

TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```
  
#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
[sample workbook](https://github.com/abhi3700/my_todo-list/blob/master/ASH09_QC_LOG_BOOK.xlsm)
```python
sht_asfe1_er = wb.sheets['ASFE1-ER']
sht_er_plot = wb.sheets['ER Plot']
df_er = sht_asfe1_er.range('A9').options(
		pd.read_excel("H:\\excel\\dryetch\\macro_enabled_logbooks\\ASH09_QC_LOG_BOOK\\ASH09_QC_LOG_BOOK.xlsm", sheetname='ASFE1-ER'), header=1, index=False
		).value
sht_er_plot.range('A1').options(index=False).value = df_er
```

**Comment by fzumstein** [comment]
You have to either use pandas or xlwings to do it, you can't mix them. Simply do:

```
sht_er_plot.range('A1').value = sht_asfe1_er.range('A9').value
```

Here, you don't need to use pandas dataframe as this would unnecessarily slow you down.

**Comment by abhi3700** [comment]
It shows this - 

Date   (MM/DD/YY)
--
in cell - A1 of the sheet_er_plot



> You have to either use pandas or xlwings to do it, you can't mix them. Simply do:
> 
> ```
> sht_er_plot.range('A1').value = sht_asfe1_er.range('A9').value
> ```
> Here, you don't need to use pandas dataframe as this would unnecessarily slow you down.

**Comment by abhi3700** [comment]
Actually, I want to plot x vs y as:
x - "Date" column
y - "Etch Rate" column
on the sht_er_plot.

That's why I was taking the help of pandas. But with my excel sheet having blank cells in both the required 2 columns, I don't know why the data is not coming as written in my version of code.

**Comment by abhi3700** [comment]
I did this - 
```py
    excel_file = pd.ExcelFile("H:\\excel\\dryetch\\macro_enabled_logbooks\\ASH09_QC_LOG_BOOK\\ASH09_QC_LOG_BOOK.xlsm")
    df_er_all = excel_file.parse('ASFE1-ER')                            # copy a sheet and paste into another sheet
    df_er = df_er_all.drop([0,1,2,3,4,5,6])                             # drop the rows with index '0' to '6'
    df_er = df_er.rename(columns=df_er.iloc[0])                         # rename the column name to row with index '0'
    df_er = df_er.reset_index(drop=True)                                # Resets the index, but adds an index column, Also dropped col by setting true.
    df_er = df_er.drop([0])                                             # remove row with index '0' which contained the column header - Date, Pre thickness, ...
    df_er = df_er[["Date (MM/DD/YY)", "Etch Rate (A/Min)"]]             # considering just 2 columns for plot
    df_er = df_er.dropna()                                              # dropping rows where at least one element is missing
```

Now, to plot-
```py
fig_er = plt.figure()
plt.plot(df_er["Date (MM/DD/YY)"], df_er["Etch Rate (A/Min)"], linestyle='-', marker='o', color='b')      # plot x vs y
sht_er_plot.pictures.add(fig_er, name= "ASFE1_ER_Plot", update= True)
```
