### ISSUE TITLE
Run-time error '-214767259 (80004004)': ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Brad-eki** [ZoomerAnalytics/xlwings#1044]
OSWindows 10

Anaconda, env: C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\

xlwings 15.2
Excel 365 (16.0.11231.20164) 32 bit
Python 3.7.2

xlwings has been installed in the anaconda env py3_7, and is confirmed not installed in the base

`xlwings quickstart myproject`
`cd myproject`

open myproject.xlsm

enable macros

Configure:-
interpreter: C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\python.exe
No PYTHONPATH
Debug UDFs: No
Log File: C:\Users\me\.xlwings
RunPython: Use UDF Server: Yes

In the myproject.py I am importing the pyxero library and trying to use it. The Python module:

===================
    import xlwings as xw
    from xero import Xero
    from xero.auth import PrivateCredentials

    def hello_xlwings():
        wb = xw.Book.caller()
        wb.sheets[0].range("A1").value = "Hello xlwings!"

        xero = None
        rsa_private_key = None
        with open('C:\\Users\\me\\Box Sync\\me\\keys\\privatekey.pem', 'rb') as f:
            rsa_private_key = f.read()
            f.close()
        credentials = PrivateCredentials('CREDENTIALS', rsa_private_key)
        xero = Xero(credentials)
        print(xero.invoices.all())
===================

Make a button, associate it with the below visual basic code:

Sub SampleCall()
    mymodule = Left(ThisWorkbook.Name, (InStrRev(ThisWorkbook.Name, ".", -1, vbTextCompare) - 1))
    RunPython ("import " & mymodule & ";" & mymodule & ".hello_xlwings()")
End Sub

When I click the button I get:

Run-time error '-214767259 (80004004)':
ImportError: DLL load failed: The specified module could not be found.

Along side this traceback:

xlwings server running, clsid={3EEC33ED-8CC6-4DC7-AE87-F12944CF9302}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\xlwings\server.py", line 287, in Exec
    exec(stmt, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\me\documents\myproject\myproject.py", line 20, in hello_xlwings
    print(xero.invoices.all())
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\xero\basemanager.py", line 189, in wrapper
    params=params, timeout=timeout)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_auth(auth, url)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\models.py", line 548, in prepare_auth
    r = auth(self)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests_oauthlib\oauth1_auth.py", line 88, in __call__
    unicode(r.url), unicode(r.method), None, r.headers)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\oauthlib\oauth1\rfc5849\__init__.py", line 314, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\oauthlib\oauth1\rfc5849\__init__.py", line 149, in get_oauth_signature
    sig = self.SIGNATURE_METHODS[self.signature_method](base_string, self)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\oauthlib\oauth1\rfc5849\signature.py", line 567, in sign_rsa_sha1_with_client
    return sign_rsa_sha1(base_string, client.rsa_key)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\oauthlib\oauth1\rfc5849\signature.py", line 559, in sign_rsa_sha1
    key = _prepare_key_plus(alg, rsa_private_key)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\oauthlib\oauth1\rfc5849\signature.py", line 640, in _prepare_key_plus
  return alg.prepare_key(keystr)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\jwt\algorithms.py", line 205, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 65, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 172, in <module>
    Binding.init_static_locks()
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 142, in init_static_locks
    __import__("_ssl")
ImportError: DLL load failed: The specified module could not be found.

I have used the pyxero module in the py3_7 env by hand and there's no problem.

I get the same result when I set the PYTHONPATH to be C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7

I can get the pyxero module running if I check Debug UDFs and run the server by hand in the myproject directory.

My guess is there's a scope discrepancy.

Is there something I've missed in terms of configuring xlwings?

**Comment by fzumstein** [comment]
Is this only a problem with the xero library? Can you try if you'd run into the same issue if e.g. using requests library?

**Comment by fzumstein** [comment]
It might be something similar to https://github.com/ZoomerAnalytics/xlwings/issues/954, i.e. the virtual env isn't properly activated at the moment.

**Comment by Brad-eki** [comment]
Attempted with requests library. This code works if I'm not using xlwings.

def httpreq():
    header = {'User-Agent': 'Mozilla/5.0', 'Authorization': 'Bearer my_bearer_code', 'Harvest-Account-Id': 'id'}
    url = 'https://api.harvestapp.com/api/v2/expenses'
    r = requests.post(url, headers=header)
    print(r.text)


xlwings server running, clsid={1C8316D5-E2E7-47E7-86D7-1EE55B004715}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\xlwings\server.py", line 287, in Exec
    exec(stmt, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\me\documents\python\acc_int_2\accounting_integration\myproject\myproject.py", line 38, in httpreq
    r = requests.post(url, headers=header)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py3_7\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.harvestapp.com', port=443): Max retries exceeded with url: /api/v2/expenses (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

I'll check out #954.

Will see if I can replicate using anaconda base.

**Comment by Brad-eki** [comment]
I have been able to replicate using anaconda base.

#954 appears to be the key.

I'm not in control of my machines install, so checking the box at the end of anaconda install isn't an option for me.

I have, however, configured my path to reflect various documentation on what is best have and this appears to have solved it.

Thank you.

**Comment by Brad-eki** [comment]
Actually, not resolved. I was having trouble with typing package being installed along side the built-in typing.

The issue I am reporting remains but may not be xlwings. It seems like the problem is in how my python (Anaconda) has been/is installed. I don't have admin access on this machine so can't follow the bouncing ball.

My PYTHONPATH in windows user environment (I don't have access to make a system variable PYTHONPATH):
C:\Users\me\AppData\Local\Continuum\anaconda3
C:\Users\me\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin
C:\Users\me\AppData\Local\Continuum\anaconda3\Library\bin
C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts
C:\Users\me\AppData\Local\Continuum\anaconda3\Lib\site-packages
C:\Users\me\AppData\Local\Continuum\anaconda3\libs
C:\Users\me\AppData\Local\Continuum\anaconda3\shell\condabin

** I don't have an anaconda3\usr\bin

The only working solution I can find is to run the server manually in the directory my .xlsm is in and use debug mode.

Kinda sux I can't get the environment configured properly as xlwings is proving to be awesome.

**Comment by fzumstein** [comment]
yes, we'll have to provide proper support for virtualenv/conda envs

**Comment by Brad-eki** [comment]
I'm engaged in another open source project at the moment but I would like to try and find a next one.

* Is the virtualenv/conda stuff difficult to support?
* Is there an understood pathway? / are you just looking for hours at the keyboard to get that supported?

Cheers

**Comment by fzumstein** [comment]
@Brad-eki let's move over to https://github.com/ZoomerAnalytics/xlwings/issues/954 with that discussion
