### ISSUE TITLE
cannot open workbook in local onedrive folder from script

### ISSUE THREAD

**Issue by lblonk** [ZoomerAnalytics/xlwings#1069]
#### 0.15.2, Office 365, Python 3.6

I think that during opening a workbook, the line 'os.path.samefile(impl.fullname, fullname)' fails, because impl.fullname returns a path to a sharepoint server (because the wb is in my onedrive folder), and os.path.samefile cannot work with this sharepoint path.

Note that i have edited the paths in the traceback below for confidentiality reasons. 

```python
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/-USERNAMEREMOVED-/Onedrive/pythonproject/main.py", line 699, in <module>
    xw.Book(r'c:\\Users\\-USERNAMEREMOVED-\\Onedrive\\pythonproject\\workbook.xlsm').set_mock_caller()
  File "C:\Users\-USERNAMEREMOVED-\Onedrive\venv\lib\site-packages\xlwings\main.py", line 488, in __init__
    impl = app.books.open(fullname).impl                                     
  File "C:\Users\-USERNAMEREMOVED-\Onedrive\venv\lib\site-packages\xlwings\main.py", line 2777, in open
    throw = not os.path.samefile(impl.fullname, fullname)
  File "C:\Users\-USERNAMEREMOVED-\AppData\Local\Python36\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://-REMOVED-.sharepoint.com/personal/-REMOVED-/workbook.xlsm'

```

**Comment by fzumstein** [comment]
Are you using `set_mock_caller()` and why? and does it work if you leave it away?

**Comment by lblonk** [comment]
Hi, indeed I am using ```set_mock_caller()```, because I'm using the script to debug functions that are meant to be called though excel normally.  

Unfortunately I've just moved the python project & workbook out of onedrive, to be able to continue to develop, so i cannot test if removing ```set_mock_caller()``` would help. I would think not, since the error occurs in the ```xw.Book()``` call and the ```set_mock_caller()``` is called after that

**Comment by fzumstein** [comment]
Yes, there's a difference in that there's no path used when you call it via RunPython which has previously been reported to work. So the strategy of developing locally when using set_mock_caller will resolve that and you should be able to run it as desired from onedrive for production. I am closing this issue, please reopen if it behaves differently from what I claim.
