### ISSUE TITLE
Issue running ga_dashboard script from Excel

### ISSUE THREAD

**Issue by selepo** [ZoomerAnalytics/xlwings#125]
I get an error when running the GA Dashboard script from the blog. (Have changed xlwings.bas to point on my installation of Winpython), but made no other changes. 

It seems to choke on getting the date from start_date ("Undantag inträffade = Exception/Error occurred")  when run from the Excel-sheet. (It works if I run it from an python interpreter). 

---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Temp\ga_dashboard\ga_dashboard.py", line 61, in refresh
    start_date = Range(sheet_dashboard, 'start_date').value
  File "C:\WinPython2\python-2.7.9\lib\site-packages\xlwings\main.py", line 429, in __init__
    self.row1 = xlplatform.get_first_row(self.xl_sheet, range_address)
  File "C:\WinPython2\python-2.7.9\lib\site-packages\xlwings\_xlwindows.py", line 123, in get_first_row
    return xl_sheet.Range(range_address).Row
  File "<COMObject <unknown>>", line 3, in Range
pywintypes.com_error: (-2147352567, 'Undantag intr\xe4ffade.', (0, None, None, None, 0, -2146827284), None)

**Comment by fzumstein** [comment]
I've now updated the blog post for xlwings v0.3.2 and also added it as an example on xlwings.org
