### ISSUE TITLE
formula method of range returns error

### ISSUE THREAD

**Issue by JohnSmizz** [ZoomerAnalytics/xlwings#183]
Hi-
I think I am the rare type of person who is looking at xlwings to use functions only available to me in XL as opposed to Python, and I thought initially xlwings would work great for that. 
However it appears the formula method of a range object isn't fully implemented to 'write' yet. In particular, I get the error 
````
Traceback (most recent call last):
  File "<ipython-input-48-c2586b491502>", line 1, in <module>
    rng.formula = "=if(1, 'hello', 'bye')"
  File "C:\Anaconda3\lib\site-packages\xlwings\main.py", line 829, in formula
    xlplatform.set_formula(self.xl_range, value)
  File "C:\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 274, in set_formula
    xl_range.Formula = value
  File "C:\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 544, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)

com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
````

I did some research and it may have something to do with Excel being in 'interactive' mode, yet I am not quite sure how to disable that setting via an xlwings property. Any idea?
See: 
http://stackoverflow.com/questions/11836319/pywin32-and-excel-exception-when-writing-large-quantities-of-data

Thanks,

**Comment by fzumstein** [comment]
Can you please paste your code that leads to this error?

**Comment by fzumstein** [comment]
closing due to inactivity. feel free to reopen.
