### ISSUE TITLE
Fresh install.

### ISSUE THREAD

**Issue by kpbleung** [ZoomerAnalytics/xlwings#439]
Hi, I am running into a few issues setting up xlwings

First, upon importing UDFs i am recieving this error:
![image](https://cloud.githubusercontent.com/assets/6257688/14412557/65d34aaa-ff22-11e5-8215-cc076d8e6aaa.png)

Second, the udf returns the following when I use a cell value as an input:

IOError: [Errno 2] No such file or directory: u'C:\\Users\\BLeung\\AppData\\Local\\Temp\\gen_py\\2.7\\00020813-0000-0000-C000-000000000046x0x1x8\\Range.py.temp'
    file = __builtin__.open(filename, mode, buffering)
  File "C:\Anaconda2\lib\codecs.py", line 896, in open
    ret = codecs.open(filename, "w", encoding)
  File "C:\Anaconda2\lib\site-packages\win32com\client\genpy.py", line 795, in open_writer
    self.file = self.open_writer(out_name)
  File "C:\Anaconda2\lib\site-packages\win32com\client\genpy.py", line 1031, in generate_child
    gen.generate_child(child, dir_path_name)
  File "C:\Anaconda2\lib\site-packages\win32com\client\makepy.py", line 318, in GenerateChildFromTypeLibSpec
    makepy.GenerateChildFromTypeLibSpec(sub_mod, info)
  File "C:\Anaconda2\lib\site-packages\win32com\client\gencache.py", line 244, in GetModuleForCLSID
    mod = GetModuleForCLSID(clsid)
  File "C:\Anaconda2\lib\site-packages\win32com\client\gencache.py", line 183, in GetClassForCLSID
    klass = gencache.GetClassForCLSID(resultCLSID)
  File "C:\Anaconda2\lib\site-packages\win32com\client\__init__.py", line 37, in __WrapDispatch
    return __WrapDispatch(dispatch, userName, resultCLSID, typeinfo, clsctx=clsctx)
  File "C:\Anaconda2\lib\site-packages\win32com\client\__init__.py", line 96, in Dispatch
    obj = win32com.client.Dispatch(obj, userName=obj.GetTypeInfo().GetDocumentation(-1)[0])
  File "C:\Anaconda2\lib\site-packages\xlwings\server.py", line 91, in FromVariant
    args = tuple(FromVariant(arg) for arg in args)
  File "C:\Anaconda2\lib\site-packages\xlwings\server.py", line 188, in <genexpr>
    args = tuple(FromVariant(arg) for arg in args)
  File "C:\Anaconda2\lib\site-packages\xlwings\server.py", line 188, in CallUDF
    return func(*args)
  File "C:\Anaconda2\lib\site-packages\win32com\server\policy.py", line 585, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Anaconda2\lib\site-packages\win32com\server\policy.py", line 282, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Anaconda2\lib\site-packages\win32com\server\policy.py", line 277, in _Invoke_

Finally, when I run a macro calling a python rountine, i get:
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "h:\analytics\daily sheet\mymodule.py", line 6, in rand_numbers

    wb = Workbook.caller()  # Creates a reference to the calling Excel file

  File "C:\Anaconda2\lib\site-packages\xlwings\main.py", line 236, in caller

    xl_app, xl_workbook = xlplatform.get_open_workbook(fullname, hwnd=sys.argv[4])

  File "C:\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 142, in get_open_workbook

    duplicate_fullnames = get_duplicate_fullnames()

  File "C:\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 124, in get_duplicate_fullnames

    for xl_app in get_xl_apps():

  File "C:\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 96, in get_xl_apps

    xl_app = get_xl_app_from_hwnd(hwnd)

  File "C:\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 72, in get_xl_app_from_hwnd

    disp = Dispatch(p)

  File "C:\Anaconda2\lib\site-packages\win32com\client\__init__.py", line 96, in Dispatch

    return __WrapDispatch(dispatch, userName, resultCLSID, typeinfo, clsctx=clsctx)

  File "C:\Anaconda2\lib\site-packages\win32com\client\__init__.py", line 37, in __WrapDispatch

    klass = gencache.GetClassForCLSID(resultCLSID)

  File "C:\Anaconda2\lib\site-packages\win32com\client\gencache.py", line 183, in GetClassForCLSID

    mod = GetModuleForCLSID(clsid)

  File "C:\Anaconda2\lib\site-packages\win32com\client\gencache.py", line 244, in GetModuleForCLSID

    makepy.GenerateChildFromTypeLibSpec(sub_mod, info)

  File "C:\Anaconda2\lib\site-packages\win32com\client\makepy.py", line 318, in GenerateChildFromTypeLibSpec

    gen.generate_child(child, dir_path_name)

  File "C:\Anaconda2\lib\site-packages\win32com\client\genpy.py", line 1031, in generate_child

    self.file = self.open_writer(out_name)

  File "C:\Anaconda2\lib\site-packages\win32com\client\genpy.py", line 795, in open_writer

    ret = codecs.open(filename, "w", encoding)

  File "C:\Anaconda2\lib\codecs.py", line 896, in open

    file = __builtin__.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: u'C:\\Users\\BLeung\\AppData\\Local\\Temp\\gen_py\\2.7\\00020813-0000-0000-C000-000000000046x0x1x8\\Window.py.temp'

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

Please asdvise.

Benny

**Comment by kpbleung** [comment]
I think I have fixed the problem.  It seems that xlwings does not like pywin32-build220; I had to use pywin32-build219 instead.  I am not sure why that's the case.  Does anyone have any thoughts?

**Comment by fzumstein** [comment]
thanks fro the update, I ll look into it!

**Comment by fzumstein** [comment]
I have no issues with pywin32 220 when installed via conda... closing this for now, please reopen if the issue persists.
