### ISSUE TITLE
Create a dropdown list and reading its values

### ISSUE THREAD

**Issue by petobens** [ZoomerAnalytics/xlwings#442]
I promise this will be my last question (at least today! thanks for the patience). 
I want to create a drop down list and then read the valuee into an Excel chart. So my question is: can I create a dropdown list directly with xlwings? Or if it cannot be done with xlwings,  can I do it with xlswriter while modifying an active xlwings workbook? 

Thanks!!!

**Comment by fzumstein** [comment]
xlsxwriter can only write new workbooks and hence you can't work on an open workbook. Anything you can do with VBA you should be able to do with xlwings, at least using the `.xl_...` attribute. If you have some VBA code that does what you want it's easier to help.

**Comment by petobens** [comment]
Can you give me a simple  example of how to create a dropdown list with xlwings and using the `.xl_` attribute? Thanks!!

**Comment by petobens** [comment]
@fzumstein Hi Felix, I'm terribly sorry to bother you again. Can you please show me, if possible, how to do this with the `.xl_` attribute? Thanks for the help and patience!

**Comment by fzumstein** [comment]
Please have a look here: https://github.com/ZoomerAnalytics/xlwings/issues/8, hope that helps

**Comment by petobens** [comment]
@fzumstein  thank you!!

**Comment by kirbyschapman** [comment]
Hello - I'm trying to find out if an item is already in a combobox (Control, not activex) that I have on a worksheet. I can add items to it just find. Then, when I'm ready to add more items to the box, I need to first see if the item is already in the box. If it is, then I want to make it the selected item. But I can't get past the point of finding out if it already exists.

Here's how I populate the box the first time around (this works great):
```
def fill_name_cb():
    # print(f'Shapes on this sheet: {ct.WS_MAIN.shapes.count}')
    cb = ct.WS_MAIN.shapes("cbNames").api.ControlFormat
    cb.RemoveAllItems()
    cb.AddItem("Select Client")
    cb.AddItem("Add New Client")
    cb.AddItem("Update List")
    # for name in ct.ASSESSMENT_ATTR["names"]:
    for name in ct.CLIENT_NAMES:
        cb.AddItem(name)
    cb.ListIndex = 1
```
This populates the box and then selects item 1 with the ListIndex method.

I've tried a variety of methods to test if each item in the box is equal to a new name. My latest effort (which doesn't work)  is:
```
    cb = ct.WS_MAIN.shapes("cbNames").api.ControlFormat
    print(f'Items in cbNames: {int(cb.ListCount)}')
    print(f'Sel Item in cbNames : {int(cb.ListIndex)}')
    number_items = int(cb.ListCount)
    print(f'Number Items: {number_items}')
    for index in range(1, number_items + 1):
        cb.ListIndex = index
        name = cb.Value # <--- this only returns the index, not the value in the box
        print(f'Value showing on combobox: {name}')
        # Crashes with the error below
        value = cb.List(index)
        print(f'value of index {index} is {value}')
```
The print results and error are:
```
cell_id B2
cell_id B2 data point: Kirby Chapman
Items in cbNames: 6
Sel Item in cbNames : 1
Number Items: 6
Value showing on combobox: 1.0 <----- Oddly this comes back as a float, but I convert it to an int
Traceback (most recent call last):
  File "c:/Users/kirby/OneDrive/calculations/helpers.py", line 158, in <module>
    retreive_assessment_data(5)
  File "c:/Users/kirby/OneDrive/calculations/helpers.py", line 94, in retreive_assessment_data
    value = cb.List(index)
  File "C:\Users\kirby\AppData\Local\Programs\Python\Python38-32\lib\site-packages\xlwings\_xlwindows.py", line 66, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\kirby\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9.py", line 6525, in List
    return self._ApplyTypes_(861, 1, (12, 0), ((12, 17),), 'List', None,Index
  File "C:\Users\kirby\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'List method of DropDown class failed', 'xlmain11.chm', 0, -2146827284), None)
```
It seems the List method is failing for some reason, and I can't figure it out. I also tried (unsuccessfully) to do this so there aren't any issues with variable types - I get the same List method failed error and never get to the print statement:
```
   cb1 = cb.List(1)
   print(cb1)
```
Can anyone help? Thanks in advance - I've been pulling my hair out over this, as it just doesn't seem that difficult.

FYI: I'm running Win 10 and have the latest updates for Excel and xlwings. Python is 3.8 and (I believe) is the 32 byte version.

**Comment by Benks-1** [comment]
Hi all!

this is what I have done:

```
def get_dropdown(xl_range: Range)->list: # type: ignore
    validation = xl_range.api.Validation
    try:
        if validation.InCellDropdown and validation.Formula1:
            formula = validation.Formula1
            if "!" in formula:
                sht, rng = formula[1:].split("!")
                value = xl_range.sheet.book.sheets[sht].range(rng).value
                if isinstance(value, str):
                    return [value]
                if isinstance(value, Iterable):
                    return value # type: ignore
            elif ":" in formula:
                value = xl_range.sheet.range(formula[1:]).value
                if isinstance(value, str):
                    return [value]
                if isinstance(value, Iterable):
                    return value # type: ignore
            elif ";" in formula:
                return list(formula.split(";"))
            else:
                return [formula]
    except Exception as err:
        raise Exception(f"Provided range {xl_range.address} does't have a defined Dropdown")
```

so I guess by setting `validation.InCellDropdown=True` and defining the `validation.Formula1` should do the trick set the dropdown?
