### ISSUE TITLE
 NaT  values throw errors

### ISSUE THREAD

**Issue by dhbachh** [ZoomerAnalytics/xlwings#443]
NaT wich is datetime's version of NaN is often times used in Pandas for empty values within a datetime type column [http://pandas.pydata.org/pandas-docs/stable/missing_data.html#datetimes](url)

Now with Xlwings support for pandas, if the dataframe happens to contains a single NaT value it throws an error in the script

Basically
 the function  set_value(xl_range,data)

in xlwings\_xlwindows.py
doesn't handle NaTs.

---------------------------
Error
---------------------------
Traceback (most recent call last):

"P:\CPM\LON\05_FORM\Scripts\PythonScripts\GenerateClientReportMapping\CRnameMapping.py", line 120, in mapToGroups

    xw.Range("Data Unique", "D8").options(index=False).value = dfMapping

  File "C:\Temp\PythonCPM\python-3.4.3\lib\site-packages\xlwings\main.py", line 882, in value

    conversion.write(data, self, self._options)

  File "C:\Temp\PythonCPM\python-3.4.3\lib\site-packages\xlwings\conversion\__init__.py", line 35, in write

    pipeline(ctx)

  File "C:\Temp\PythonCPM\python-3.4.3\lib\site-packages\xlwings\conversion\framework.py", line 66, in __call__

    stage(*args, **kwargs)

  File "C:\Temp\PythonCPM\python-3.4.3\lib\site-packages\xlwings\conversion\standard.py", line 62, in __call__

    ), ctx.value)

  File "C:\Temp\PythonCPM\python-3.4.3\lib\site-packages\xlwings\_xlwindows.py", line 326, in set_value

    xl_range.Value = data

  File "C:\Temp\PythonCPM\python-3.4.3\lib\site-packages\win32com\client\dynamic.py", line 560, in __setattr__

    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)

  File "pandas\tslib.pyx", line 663, in pandas.tslib._make_error_func.f (pandas\tslib.c:14736)

ValueError: NaTType does not support astimezone

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by sean-violante-lendico** [comment]
![image](https://cloud.githubusercontent.com/assets/11405896/15603627/1277b374-23fc-11e6-8a8f-57fca4bc8273.png)
using xlwings 4.72/4.71 I get the above error when I use NaT
