### ISSUE TITLE
the executable file converted by pyinstaller can't run

### ISSUE THREAD

**Issue by ReservoirSimulator** [ZoomerAnalytics/xlwings#854]
Environment:
Python version: 3.6

Question describe:
When I added 'import xlwings as xw', the executable file converted by pyinstaller can't run, and the line number of error is the line of 'import xlwings as xw'. But if I remove xlwings and its related code, the converted exe can run. Is there anything I missed?

> (base) E:\test\dist\myproject>myproject.exe
>Traceback (most recent call last):
>  File "myproject.py", line 7, in <module>
>  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

>"""
>Copyright (C) 2014-2016, Zoomer Analytics LLC.
>All rights reserved.
>
>License: BSD 3-clause (see LICENSE.txt for details)
>"""
>import xlwings as xw
>
>
>def fibonacci(n):
>   """
>    Generates the first n Fibonacci numbers.
>    Adopted from: https://docs.python.org/3/tutorial/modules.html
>    """
>    result = []
>    a, b = 0, 1
>    while len(result) < n:
>        result.append(b)
>        a, b = b, a + b
>    return result
>
>

>if __name__ == "__main__":
    # Used for frozen executable
>    print(fibonacci(4))
>

**Comment by fzumstein** [comment]
i think freezers don't like print, but I might be wrong. Otherwise try to ask on the pyinstaller side.

**Comment by ReservoirSimulator** [comment]
Here print is just the debug purpose.  What's the version of pyinstaller which is OK for runfrozenpython?

**Comment by jsaurabh36** [comment]
I am having exactly same problem. Executable seems to work perfectly on one machine and very slow on other and seem to wait at line "import xlwing as xw" for almost 2mins. Looks like some kind of setting on device vs the another any help would be appreciated. below is trace
Traceback (most recent call last):
  File "SSimulation.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "xlwings\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "xlwings\_xlwindows.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "xlwings\utils.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "numpy\__init__.py", line 153, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "numpy\lib\__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 478, in exec_module
  File "PyInstaller\loader\pyimod03_importers.py", line 298, in get_code
  File "PyInstaller\loader\pyimod02_archive.py", line 290, in extract
  File "PyInstaller\loader\pyimod02_archive.py", line 87, in __enter__
KeyboardInterrupt
[14532] Failed to execute script 'SSimulation' due to unhandled exception!

**Comment by hghaffari** [comment]
As soon as I add 'import xlwings as xw' at the top of my python file and use the previously executable file by rerunning:
pyinstaller --onefile myscript.py 
after completing a successful conversion to myscript.exe the new executable fails to run!!
