### ISSUE TITLE
Automation Error 440

### ISSUE THREAD

**Issue by bushidoji** [ZoomerAnalytics/xlwings#898]
I've tried to import UDF but get "Automation error 440"

Windows 7 32-bit
Microsoft Excel 2016 (Office 365)
Python 3.6 
Anaconda 5.2
xlwings: 0.11.5 (I believe... will circle back to confirm.. installed via conda)

I tried to troubleshoot this issue using suggestions online, to no avail...  I get the same 'automation error' when trying to import UDF's through the "quickstart" template file / from prompt.

Any other information I can provide, please let me know..

**Comment by DougAJ4** [comment]
Do you have any other modules (other than xlwings_udfs).

I get that message if I already have a function in another module with the same name as one I am trying to import.

**Comment by bushidoji** [comment]
troubleshooting online I've heard others say as much, but I have no other modules.  

Again, I'm having this error using the quick start

**Comment by bushidoji** [comment]
bump - any ideas on how I can get xlwings to work?

**Comment by fzumstein** [comment]
Have you enabled Trust access to VBA project object model? See http://docs.xlwings.org/en/stable/udfs.html#one-time-excel-preparations

**Comment by fzumstein** [comment]
could you make xlwings work in the end?

**Comment by Ringur** [comment]
I'm running into the same problem as described above.

I have the following setup:
Windows 10 (10.0.17763)
Microsoft Excel 2016 (Office 365)
Python 3.7.1
conda 4.5.12
xlwings: 0.11.8

It had been running fine since last fall but all of a sudden I started getting this error.

The most basic quickstart project yields the error and I have enabled Trust access...

**Comment by fzumstein** [comment]
any update on Excel or conda recently?

**Comment by Ringur** [comment]
There was an Excel update in February which may have something to do with this. The current Excel version is 1808, build 10730.20280.

conda hasn't been updated.

**Comment by fzumstein** [comment]
might be worth to repair Office (if you have access to that) and reboot, then check again...

**Comment by Ringur** [comment]
Tried that already as well as uninstall Office, restart, re-install Office and restart again. Same with conda, python and xlwings, did a full uninstall and then re-install and the error was still there.

**Comment by fzumstein** [comment]
Can you unlock the xlwings VBA project (password `xlwings`) and see where it breaks in the code? Then get some more details when typing `?Err.Description` in the immediate window?

**Comment by Ringur** [comment]
It fails in ImportPythonUDFs() and throws ImportError with the following Err details:

> ?Err.Description
> Automation error
> ?Err.Number
>  440 
> ?Err.Source
> xlwings

**Comment by Ringur** [comment]
Output from python when error happens:

```
In [1]: runfile('C:/Users/hda/Documents/debug_project/debug_project.py', wdir='C:/Users/hda/Documents/debug_project')

xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}

pythoncom error: Python error invoking COM method.



Traceback (most recent call last):

  File "C:\Users\hda\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_

    return self._invoke_(dispid, lcid, wFlags, args)

  File "C:\Users\hda\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_

    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)

  File "C:\Users\hda\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_

    return func(*args)

  File "C:\Users\hda\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\server.py", line 186, in Call

    return ToVariant(getattr(obj, method)(*pargs, **kwargs))

  File "C:\Users\hda\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\udfs.py", line 367, in import_udfs

    xl_workbook.VBProject.VBComponents.Import(tf.name)

  File "<COMObject <unknown>>", line 2, in Import

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146828281), None)
```

**Comment by fzumstein** [comment]
Does running a formula work (that you had imported previously)? i.e. is only the Import step causing an issue?

**Comment by fzumstein** [comment]
and to ask the obvious: is Trust access to VBA project object model still enabled?

**Comment by Ringur** [comment]
Yes, running a formula from an old import works as well as running a macro that is hooked to python code.

The 'Trust access to VBA project object model' is still enabled.

**Comment by Ringur** [comment]
Note: have 4 computers and two of them get the error while the other two don't. All 4 should have the same versions of Excel.

**Comment by fzumstein** [comment]
Here's what you can try: On one of the machines where it's working: Export the VBA module xlwings_udfs and manually import it on one of the machines where it fails. Does that work?

**Comment by Ringur** [comment]
When I do Import file... in VBA I get an 'Out of memory' error. If I however manually copy-paste the code into a newly created module in VBA it works. This is a workaround but it's quite cumbersome.

**Comment by Ringur** [comment]
This is typical, the bug is gone... There was an Windows update that ran during the night and this morning I had no problems. Quite annoying not knowing what caused it but it is fixed for now. Thanks for the help.

**Comment by fschuhi** [comment]
I had the same problem, had a parameter named "type" in an @xw.func, no 440 after I changed the name.

**Comment by whoopnip** [comment]
I also ran into this where the parameter "case" was trying to be used. After switching the name it worked properly. It seems we must always avoid VBA reserved names for UDF parameters or it will conflict with the VBA code. It now seems obvious in retrospect, but perhaps the docs should be updated to mention this.

**Comment by rahullak** [comment]
Sorry to bump, but adding another relevant scenario.

Also, to add another scenario where this error occurs:

If your python filename is different from the @xw.sub function inside your python file, you get this error.

Ideally the error message should reflect that.

**Comment by fzumstein** [comment]
@rahullak hm not sure I follow, can you add a full example please?

**Comment by rahullak** [comment]
@fzumstein 

I mean that if your python filename is "trial.py" and a single python function (decorated as @xw.sub) inside that file is named "get_trial.py", and if we try to import UDF function we get "Automation Error 440", even though "Trust access to VBA project object model" is enabled.

However, this doesn't happen always as I have learned after making previous post. The issue seems to have resolved itself somehow and I am unable to replicate the issue again - meaning now, even though the python file name and the function inside it have different names, the import works. 

Sorry, it is a little strange behaviour. If I face it again, I'll try to capture the steps that lead to it.

**Comment by buellboy** [comment]
Hello Felix! I'm loving xlwings so far! Specially the SQL function,
I ran into Error 440 and there is one **really** simple thing to check if you are getting this error.
My use case is to move out of VBA to python for a variety of reasons. 
In my situation (which I am sure is familiar), I had a problem because I named on of the functions (in python) getBinanceData().

The problem is that I had  **already a function named getBinanceData()** in my VBA within the file i was opening. Whenever I imported, I would get error 440 and I could not understand why. I then opened the sheet this morning and I had a "duplicate declaration in scope error". 

I renamed the function in python and now the import works flawlessly!
