### ISSUE TITLE
xlwings crashes if imported after clr (pythonnet)

### ISSUE THREAD

**Issue by akasolace** [ZoomerAnalytics/xlwings#997]
OS: Windows 8
XLwings: 0.11.4
Excel: 2016
Python 3.7

#### 
xlwings crashes if imported after clr (pythonnet), however, it works fine if imported before.

```python
Traceback (most recent call last):
   line 6, in <module>
    import xlwings as xw
  File xlwings\__init__.py", line 23, in <module>
    from . import _xlwindows as xlplatform
  File "xlwings\_xlwindows.py", line 25, in <module>
    from comtypes import IUnknown
  File comtypes\__init__.py", line 165, in <module>
    CoInitializeEx()
  File comtypes\__init__.py", line 156, in CoInitializeEx
    _ole32.CoInitializeEx(None, flags)
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set


```

#### to reproduce the bug

```python
import clr
import xlwings as xw
```

**Comment by denfromufa** [comment]
this should solve the issue:

https://github.com/pythonnet/pythonnet/issues/108
